# Generated by Django 3.2.9 on 2021-12-03 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('caption', models.CharField(default=None, max_length=500)),
                ('image', models.CharField(default=None, max_length=500)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
